# Generated by Django 4.2.27 on 2026-09-30 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_useremploymenthistory_soc_detailed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIntakeTargetSkillXref',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
